### PR TITLE
Added Code of Conduct

### PR DESCRIPTION
**Pull request by siddhantprateek**
This solves issue #2

### CODE REVIEW

**Comment by aakankshabhende** [comment]
Hey @siddhantprateek 
did you get email to contribute in this project?

**Comment by siddhantprateek** [comment]
No, not yet isn't the coding period have started.

**Comment by aakankshabhende** [comment]
Emails have been sent. The one who got email only can contribute to the project

**Comment by siddhantprateek** [comment]
Exactly from whom do we get the email?

**Comment by siddhantprateek** [comment]
I have not received any emails regarding contributing to this project, and I guess I have to close this PR. Sorry for the disruption.

**Comment by aakankshabhende** [comment]
> I have not received any emails regarding contributing to this project, and I guess I have to close this PR. Sorry for the disruption.

It's alright @siddhantprateek . No worries :)

**Pull request closed without merging**
